### ISSUE TITLE
Framework / tech standard to follow

### ISSUE THREAD

**Issue by timpamungkas** [ferdinalcandra/fc#12]
Technology :
spring boot 2.x + gradle (via start.spring.io), latest
JDK 15 via OpenJDK
 
 - Spring web, JPA via hibernate, Spring RabbitMQ, lombok (spring boot stack untuk development microservice)
 - Spring Rest repositories diperbolehkan untuk speed up CRUD API
 - Springdoc untuk create swagger
 - openfeign (untuk web client, hindari RestTemplate atau low-level client untuk reduce code)
 - resilience4j (untuk mekanisme resilisent API (e.g. retry / circuit breaker))
 - codecentric admin client (for monitoring)
 - sleuth
 - Unit test via JUnit : coverage target 60%
 
In case additional yech required :
 - freemarker (kalau perlu templating engine)
 - Quartz with persistence (e.g. database) scheduler, kalau perlu scheduler complex. Kalau schedulernya simple, silakan gunakan spring @Scheduled dengan durais di-externalize ke file .yml terpisah
 
Architecture & source code organization:
 - Adopt hexagonal architecture & CQS. Contact timo untuk detail template nya

**Comment by ferdinalcandra** [comment]
![1](https://user-images.githubusercontent.com/74760989/111125935-bacc1600-85a4-11eb-84dc-f02a8fade47a.jpeg)
https://commons.apache.org/proper/commons-vfs/filesystems.html
masih belum directly supported dengan vfs

![2](https://user-images.githubusercontent.com/74760989/111125992-cb7c8c00-85a4-11eb-98d9-3d08e390b851.jpeg)
https://commons.apache.org/proper/commons-vfs/testing.html
dan belum tested juga

**Comment by timpamungkas** [comment]
unused
